### ISSUE TITLE
Backup l'ancien site

### ISSUE THREAD

**Issue by EmmanuelDemey** [GDG-Lille/devfest-lille#45]
Je pense que le site du DevFest Lille 2017 doit toujours être disponible online pour pouvoir communiquer dessus. 
Pour commencer, il faudrait par exemple copier l'ancien site dans un sous repertoire **2017** par exemple. 
Dans le footer de le nouvelle application, il faudra ajouter la liste des anciennes éditions
Et ensuite, commencer à améliorer celui disponible à la racine pour le DevFest 2018. 
Make sense ?

**Comment by fgruchala** [comment]
#48
