### ISSUE TITLE
Changer couleur barre navigateur sur mobile

### ISSUE THREAD

**Issue by FannyDemey** [GDG-Lille/devfest-lille#60]
![image](https://user-images.githubusercontent.com/3006608/33995263-bd66c51e-e0dd-11e7-8465-359b76212020.png)

**Comment by fgruchala** [comment]
Corrigé @FannyDemey 
![screenshot_20180101-122417](https://user-images.githubusercontent.com/12196721/34467337-dbe5b27e-eeee-11e7-8645-e46e877e10c3.png)
