### ISSUE TITLE
Bouton Ajouter à son agenda, n'ouvre pas la bonne date de google cal

### ISSUE THREAD

**Issue by FannyDemey** [GDG-Lille/devfest-lille#64]
@fgruchala

**Comment by fgruchala** [comment]
https://calendar.google.com/calendar/r/eventedit?text=Devfest+Lille&dates=20180621T070000Z/20180621T170000Z&details=Plus+d%27infos+ici:+https://devfest.gdglille.org&location=IMT+Lille+Douai+20+Rue+Guglielmo+Marconi+59650+Villeneuve-d%27Ascq&sf=true&output=xml#eventpage_6

**Comment by fgruchala** [comment]
<img width="1280" alt="capture d ecran 2017-12-20 a 12 19 02" src="https://user-images.githubusercontent.com/12196721/34204705-fbb18858-e57f-11e7-8ada-dfeac69b03b2.png">

**Comment by fgruchala** [comment]
chez moi, si apparement :D 
OK OK il manque les heures, c'est corrigé

**Comment by fgruchala** [comment]
<img width="1280" alt="capture d ecran 2017-12-20 a 12 20 15" src="https://user-images.githubusercontent.com/12196721/34204754-262d3b2c-e580-11e7-9406-1b3311037cf7.png">
