### ISSUE TITLE
Afficher nombre d'attendee, nombre de track, nombre de session et nombre de speaker

### ISSUE THREAD

**Issue by FannyDemey** [GDG-Lille/devfest-lille#65]
https://devfest.gdgnantes.com/

**Comment by FannyDemey** [comment]
je viens d'ajouter angela sur le repo, je lui ai demandé de jeter un oeil à ce point.

**Comment by gericci** [comment]
Ok. Je vais voir ça (du moment qu'on n'appelle pas les speakers de "superhéros")

**Comment by FannyDemey** [comment]
ahah oui c'était pour l'exemple :)
