### ISSUE TITLE
Mettre les logos de Sfeir (Gold), Vaduo Consulting (Silver) et Proxiad (Silver)

### ISSUE THREAD

**Issue by EmmanuelDemey** [GDG-Lille/devfest-lille#68]

**Comment by EmmanuelDemey** [comment]
![logohd](https://user-images.githubusercontent.com/555768/34374381-2f425e3e-eae1-11e7-9dd9-ed7189c835dd.png)

**Comment by EmmanuelDemey** [comment]
![logovector_alt](https://user-images.githubusercontent.com/555768/34374388-3629020c-eae1-11e7-84f2-cd94c6bc6512.png)

**Comment by EmmanuelDemey** [comment]
![logosfeir28129](https://user-images.githubusercontent.com/555768/34374448-77755a30-eae1-11e7-9f56-47b3605b6d6b.png)

**Comment by fgruchala** [comment]
En plus, @Gillespie59 à fait ça bien avec une issue, quel talent :)

**Comment by fgruchala** [comment]
Done
![localhost_8081_ nexus 5x 1](https://user-images.githubusercontent.com/12196721/34467415-71d1eeea-eef1-11e7-8492-c35e5a732e00.png)

<img width="1280" alt="capture d ecran 2018-01-01 a 12 38 21" src="https://user-images.githubusercontent.com/12196721/34467416-7844c428-eef1-11e7-9d47-4b9211cff28c.png">
